# Codecov (https://codecov.io/gh/dubreuia/intellij-plugin-save-actions)

# remove comments for pull requests
comment: off

# remove code from analysis
ignore:
  # remove ui code that cannot be tested in intellij
  - "src/main/java/com/dubreuia/ui/"
  # remove external code
  - "src/main/java/com/intellij/"
  # remove external code
  - "src/main/java/com/siyeh/"
