# Code Climate (https://codeclimate.com/github/dubreuia/intellij-plugin-save-actions)
version: "2"

# add checkstyle and sonar
plugins:
  checkstyle:
    enabled: true
    config:
      file: "config/checkstyle/save-actions.xml"
  sonar-java:
    enabled: true

# remove code from analysis
exclude_patterns:
  # remove external code
  - "src/main/java/com/intellij/**"
  # remove external code
  - "src/main/java/com/siyeh/**"
  # remove test resources (there are java files for tests)
  - "src/test/resources/**"
