# lgtm (https://lgtm.com/projects/g/dubreuia/intellij-plugin-save-actions/)

# Remove external code from analysis (this doesn't work for now)
extraction:
  java:
    before_index:
      exclude:
        - "src/main/java/com/intellij/**"
        - "src/main/java/com/siyeh/**"
